### PR TITLE
Update to Sphinx 1.6

### PR DESCRIPTION
**Pull request by i80and**
Addresses #127

### CODE REVIEW

**Comment by Letme** [comment]
We could use below if-else to have backwards compatibility:
```
import sphinx
if sphinx.__version__ < '1.6.0':
    from sphinx.theming import Theme
else:
```

**Comment by i80and** [comment]
I tweaked the tests and put in place some compatibility shims

**Comment by Letme** [comment]
Waw nice job. 
Can you also add a tox env for sphinx 1.5 and 1.6 to keep this in a bit better shape for the future?

**Comment by i80and** [comment]
As requested

**Comment by Letme** [comment]
I have tested this on my local repos with sphinx 1.6.3 (`pip install https://github.com/i80and/hieroglyph/tree/fix-sphinx-16`) and it works as expected.

I think version needs to be bumped as well (no idea how @nyergler does that) as there is a version variable inside the setup.py.

Quite excited I must say.

**Comment by nyergler** [comment]
This looks great, thanks @i80and! I'm going to merge this so that it's on `master`.

The outstanding thing for full 1.6 support is #120; I'll take a look at that this evening. Regardless, I'll cut a new version this evening. (If I can't easily fix quickstart, I'll make it fail gracefully on 1.6 with a pointer to the Hieroglyph docs rather than crashing.)

Thanks again, @i80and, much appreciated! 

🎉

**Pull request merged**
